apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-storage-pvc
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
  selector:
    matchLabels:
      tier: "mysql"
